<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../static/css/login.css">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <title>ProjectTool</title>
</head>
<body>
<div>Тут будет страница приветствия и прочая фигня, еще кнопки реги и логина</div>
<a href="/home">Home page</a>
<a href="/login">Login</a>
<a href="/registration">Registration</a>
</body>
</html>